### ISSUE TITLE
Ability to hide a token from the list

### ISSUE THREAD

**Issue by PeachfolioCryptoApe** [Peachfolio/V1-Beta#8]
Raised by Anonim. 

They'd like the ability to remove tokens from being displayed. Would need on/off configuration held outside of the token list with maybe the first hide action as a slider action. 

Dependency: Will need to consider how this ties in with the future extensibility towards other chains. We may wish to have this for both type level and token level.

**Comment by cyberyugun** [comment]
I have 2 ideas : 
1. create a search field to find the token we want to find and when it is successfully searched for example on the left of the coin details and on the right of the toogle to turn on / off to display coins such as trust wallet

2. create a tab for favorite tokens that have been invested so when we are on the homepage page, there are all the tokens that we invest then click our favorite token for token details and there is a favorite button either a star or a heart then when finished pressing, the token will appear in the newly created tab

note : don't forget the search token feature because for example we have a lot of tokens, this will make it difficult for us to find it without this search feature
